<template>
  <div class="search__wrap" id="search-top">
    <h1 class="text-2xl mx-auto my-6 w-64 text-center font-bold">Search All Activities</h1>
    <div class="search-wrap">
      <label>
        <div class="w-64 mx-auto pb-2">Keyword:</div>
        <input
          type="text"
          v-model="searchTerm"
          class="block border rounded-lg border-gray-500 border-solid text-lg p-2 center mx-auto w-64"
        />
      </label>

      <div class="flex justify-center mt-6 flex-col sm:flex-row">
        <label class="p-4 text-center sm:text-left">
          <div class="pb-2">Filter by location:</div>
          <select
            class="border rounded border-gray-500 w-64 sm:w-auto"
            name="location"
            id="location"
            v-model="chosenLocation"
          >
            <option v-for="location in locations" :value="location" :key="location">{{location}}</option>
          </select>
        </label>
        <label class="p-4 text-center sm:text-left">
          <div class="pb-2">Filter by age range:</div>
          <select
            class="border rounded border-gray-500 w-64 sm:w-auto"
            name="age"
            id="age"
            v-model="chosenRange"
          >
            <option v-for="range in ageRanges" :value="range" :key="range">{{range}}</option>
          </select>
        </label>
        <div class="self-end w-40">
          <transition name="fade" mode="out-in">
            <button
              v-if="searchTerm.length || chosenRange.length || chosenLocation.length"
              class="md:self-end border border-blue-500 rounded my-4 px-6 block mx-auto"
              @click="clear"
            >Clear Search</button>
          </transition>
        </div>
      </div>
    </div>

    <transition name="fade" mode="out-in">
      <div :key="searchTerm.length">
        <p class="my-10 text-xl">
          Results found
          <span v-if="searchTerm.length">for "{{searchTerm}}"</span>
          <span v-if="chosenLocation.length">matching location "{{chosenLocation}}"</span>
          <span v-if="chosenLocation.length && chosenRange.length">and</span>
          <span v-if="chosenRange.length">matching age range "{{chosenRange}}"</span>:
          <b>{{filteredResults.length}}</b>
        </p>
        <article
          class="results-card__wrap feature p-2 text text-base leading-tight my-6 border border-solid"
          v-for="(item, i) in filteredResults"
          :key="item.Name + i"
        >
          <ul class="results-card">
            <li>
              <div class="text-xl font-semibold pb-1">{{item.Name}}</div>
            </li>
            <li v-if="item.Category || item['Banner']">
              {{item.Category}}
              <span v-if="item.Category && item['Banner']">-</span>
              {{item["Banner"]}}
            </li>
            <li v-if="item['Member only?'].toLowerCase() == 'y'" class="italic">Member Only</li>
            <li>Details: {{item["Event details"]}}</li>
            <li v-if="item['When?']">When?: {{item["When?"]}}</li>
            <li>Cost: {{item["Cost €"]}}</li>
            <li>Age: {{item["Age"]}}</li>
            <li v-if="item['Special notes']">Special Notes: {{item["Special notes"]}}</li>
            <li>
              Location: {{item["Address 1"]}}
              <span v-if="item['Address 2']">/</span>
              {{item["Address 2"]}}
              <span v-if="item['Address 3']">/</span>
              {{item["Address 3"]}}
              <span v-if="item['Address 4']">/</span>
              {{item["Address 4"]}}
            </li>
            <li v-if="item['Postcode']">Post Code: {{item["Postcode"]}}</li>
            <li v-if="item['Website/Facebook']">
              Website/Facebook:
              <a
                :href="item['Website/Facebook']"
                class="text-sm font-thin"
              >{{item["Website/Facebook"]}}</a>
            </li>
            <li v-if="item['Tel:']">Tel: {{item["Tel:"]}}</li>
            <li>Contact: {{item["Address 1"]}}</li>
            <!-- <li v-for="(val, key) in item" :key="key" v-show="val">
              <div class="text-xs">{{key}}</div>
              <div class="text-lg result-val">
                <a v-if="key == 'Website/Facebook'" :href="val" class="text-sm font-thin">{{val}}</a>
                <button
                  v-else-if="searchOptions.keys.includes(key)"
                  @click="searchFromClick"
                  class="clickable-val"
                >{{val}}</button>
                <span v-else>{{val}}</span>
              </div>
            </li>-->
          </ul>
        </article>
      </div>
      <!-- <div v-if="!searchTerm.length" :key="searchTerm.length">
        <article
          class="results-card__wrap feature p-2 text text-base leading-tight my-6 border border-solid"
          v-for="(item, i) in items"
          :key="item.Name + i"
        >
          <ul class="results-card">
            <li v-for="(val, key) in item" :key="key" v-show="val">
              <div class="text-xs text-bold">{{key}}</div>
              <div class="text-lg result-val">
                <a v-if="key == 'Website/Facebook'" :href="val" class="text-sm font-thin">{{val}}</a>
                <button
                  v-else-if="searchOptions.keys.includes(key)"
                  @click="searchTerm = val"
                  class="clickable-val"
                >{{val}}</button>
                <span v-else>{{val}}</span>
              </div>
            </li>
          </ul>
        </article>
      </div>-->
    </transition>
  </div>
</template>

<script>
import scrollToElement from "scroll-to-element";

export default {
  props: ["blok"],
  data() {
    return {
      searchTerm: "",
      chosenLocation: "",
      chosenRange: "",
      results: [],
      fuse: null,
      allKeys: [
        "Name",
        "Category",
        "Organisation",
        "Address 1",
        "Address 2",
        "Address 3",
        "Banner/Event details"
      ],
      searchOptions: {
        keys: [
          "Name",
          "Category",
          "Organisation",
          "Address 1",
          "Address 2",
          "Address 3",
          "Banner/Event details"
        ],
        threshold: 0.4
      },
      locations: [],
      ageRanges: [],
      items: [
        {
          Name: "Prism",
          Category: "Group",
          Organisation: "Prism",
          "Member only?": "n/a",
          Banner: "Local autism group",
          "Event details":
            "Support group for families in Dun Laoghaire Rathdown",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "n/a",
          "Recurs?": "n/a",
          "Recurring frequency": "n/a",
          "Last date": "n/a",
          Age: "All",
          "Special notes": "",
          "Address 1": "Dublin",
          "Address 2": "Dun Laoghaire",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Prism Helpline",
          Category: "Support",
          Organisation: "Prism",
          "Member only?": "CHK",
          Banner: "Helpline",
          "Event details": "Call +353 85 8292839",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?": "1000 - 1300 Monday to Friday",
          "First Date": "",
          Time: "1000-1300 Mon-Fri",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "Dublin",
          "Address 2": "Dun Laoghaire",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Prism Meetings",
          Category: "Support",
          Organisation: "Prism",
          "Member only?": "Y",
          Banner: "Parent Support Meetings",
          "Event details": "Children can also attend meetings",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?": "Monthly",
          "First Date": "",
          Time: "Monthly TBC",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "Dublin",
          "Address 2": "Dun Laoghaire",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Prism Teen Youth",
          Category: "Activity",
          Organisation: "Prism",
          "Member only?": "CHK",
          Banner: "Weekly teen youth group",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?": "Weekly",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "13+",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Freedom Surf School",
          Category: "Activity",
          Organisation: "Freedom Surf School",
          "Member only?": "N",
          Banner: "Surf Lessons",
          "Event details":
            "Private surf lessons with ASD friendly instructors, parents must stay and are welcome to join in the water",
          "": "",
          __1: "",
          "Cost €": 100,
          "When?": "As booked",
          "First Date": "n/a",
          Time: "n/a",
          "Recurs?": "Y",
          "Recurring frequency": "Daily",
          "Last date": "n/a",
          Age: "All",
          "Special notes": "",
          "Address 1": "Waterford",
          "Address 2": "Tramore",
          "Address 3": "Riverstown",
          "Address 4": "The Gap",
          Postcode: "X91 Y436",
          "Website/Facebook": "www.freedomsurfschool.com",
          "Tel:": 353863914908,
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "High Rise",
          Category: "Activity",
          Organisation: "High Rise",
          "Member only?": "N",
          Banner: "Adventure Centre",
          "Event details": "Climbing, sensory room, quiet room, soft play",
          "": "",
          __1: "",
          "Cost €": "Varies by activity",
          "When?": "Opening hours XXX",
          "First Date": "n/a",
          Time: "n/a",
          "Recurs?": "Y",
          "Recurring frequency": "Daily",
          "Last date": "n/a",
          Age: "All, up to 8 for Softplay",
          "Special notes": "",
          "Address 1": "Antrim",
          "Address 2": "Lisburn",
          "Address 3": "Blaris Industrial Estate",
          "Address 4": "11A Altona Road",
          Postcode: "BT27 5QB",
          "Website/Facebook": "https://highriseni.org/",
          "Tel:": 442892636195,
          "Contact name": "Adam Louden",
          "Contact details": "",
          "Follow up": "email follow to LinkedIn outreach"
        },
        {
          Name: "SuperValu",
          Category: "Autism Friendly",
          Organisation: "SuperValu",
          "Member only?": "N",
          Banner: "Autism friendly shopping",
          "Event details": "n/a",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Longford Swimming",
          Category: "Activity",
          Organisation: "MWB Longford",
          "Member only?": "CHK",
          Banner: "Swimming and inflatables",
          "Event details": "Swimming session with large inflatable in pool",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "TBC",
          "First Date": "17.08.2019",
          Time: "tbc",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "tbc",
          "Special notes": "",
          "Address 1": "Longford",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Longord Christmas",
          Category: "Activity",
          Organisation: "MWB Longford",
          "Member only?": "CHK",
          Banner: "Christmas Party",
          "Event details": "Annual Christmas party",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?": "14 December 2019",
          "First Date": "14.12.2019",
          Time: "tbc",
          "Recurs?": "Y",
          "Recurring frequency": "Annual",
          "Last date": "n/a",
          Age: "All",
          "Special notes": "",
          "Address 1": "call Michael 087 9877 342",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "MWB Longford",
          Category: "Group",
          Organisation: "MWB Longford",
          "Member only?": "n/a",
          Banner: "Local autism group",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "tbc",
          "Special notes": "",
          "Address 1": "Longford",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "Michael, chairperson",
          "Contact details": "087 9877 342",
          "Follow up": ""
        },
        {
          Name: "Sensory Me",
          Category: "Autism Friendly",
          Organisation: "Roscommon",
          "Member only?": "N",
          Banner: "Sensory play",
          "Event details": "Sensory play including lego therapy",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?":
            "Thursdays 2-6pm; Fridays 2-6pm, Saturdays 10am-2pm, Sunday 11am-2pm, plus other times by arrangement",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "Roscommon",
          "Address 2": "Goff Street",
          "Address 3": "",
          "Address 4": "",
          Postcode: "F42W928",
          "Website/Facebook": "https://www.facebook.com/sensorymeireland/",
          "Tel:": "",
          "Contact name": "suggestion",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Shannon Airport",
          Category: "Autism Friendly",
          Organisation: "Shannon Airport",
          "Member only?": "n/a",
          Banner: "Sensory room and assistance",
          "Event details": "Sensory Room and assistance through airport",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?": "During airport operating hours",
          "First Date": "n/a",
          Time: "All",
          "Recurs?": "Y",
          "Recurring frequency": "Daily",
          "Last date": "n/a",
          Age: "All",
          "Special notes": "",
          "Address 1": "Clare",
          "Address 2": "Shannon",
          "Address 3": "",
          "Address 4": "",
          Postcode: "V14EE06",
          "Website/Facebook":
            "https://www.shannonairport.ie/passengers/at-the-airport/flying-out/passenger-assistance/autism-special-needs/",
          "Tel:": "",
          "Contact name": "Orla",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Dublin Airport",
          Category: "Autism Friendly",
          Organisation: "Dublin Airport",
          "Member only?": "n/a",
          Banner: "Sensory Room and assistance",
          "Event details": "Sensory Room and assistance through airport",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?": "During airport operating hours",
          "First Date": "n/a",
          Time: "All",
          "Recurs?": "Y",
          "Recurring frequency": "Daily",
          "Last date": "n/a",
          Age: "All",
          "Special notes": "",
          "Address 1": "Dublin",
          "Address 2": "Dublin Airport",
          "Address 3": "",
          "Address 4": "",
          Postcode: "K67 V8P7",
          "Website/Facebook":
            "https://www.dublinairport.com/at-the-airport/help-and-support/travelling-with-autism",
          "Tel:": "",
          "Contact name": "Siobhan",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Alongside Social",
          Category: "Activity",
          Organisation: "Baldoyle Family Resource Services Group",
          "Member only?": "N",
          Banner: "Social group for children and families",
          "Event details": "Sensory toys, parent support, siblings welcome",
          "": "",
          __1: "",
          "Cost €": "€2 per family",
          "When?": "Thursdays 2.45pm to 4.30pm during term time",
          "First Date": "n/a",
          Time: "Thursdays 2.45pm to 4.30pm during term time",
          "Recurs?": "Y",
          "Recurring frequency": "Weekly",
          "Last date": "n/a",
          Age: "Approx 4-8",
          "Special notes": "",
          "Address 1": "Dublin",
          "Address 2": "Dublin 13",
          "Address 3": "Grange Road",
          "Address 4": "Baldoyle Family Resource Services",
          Postcode: "D13 TE80",
          "Website/Facebook":
            "https://www.facebook.com/baldoylefamilyresourcecentre/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Alongside Social Clinics",
          Category: "Support",
          Organisation: "Baldoyle Family Resource Services Group",
          "Member only?": "N",
          Banner:
            "Monthly support meetings for parents of children with additional needs",
          "Event details": "Parent support",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "Monthly",
          "First Date": "",
          Time: "TBC",
          "Recurs?": "Y",
          "Recurring frequency": "Monthly",
          "Last date": "n/a",
          Age: "All",
          "Special notes": "Consulting with parents on topics",
          "Address 1": "Dublin",
          "Address 2": "Dublin 13",
          "Address 3": "Grange Road",
          "Address 4": "Baldoyle Family Resource Services",
          Postcode: "D13 TE80",
          "Website/Facebook":
            "https://www.facebook.com/baldoylefamilyresourcecentre/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Cul Camp",
          Category: "Activity",
          Organisation: "Wexford GAA",
          "Member only?": "N",
          Banner: "GAA skills",
          "Event details": "GAA skills, siblings welcome, parents must stay",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?": "1130 to 1300 from Aug 6 to Aug 8 2019",
          "First Date": 43624,
          Time: "1130-1300",
          "Recurs?": "Y",
          "Recurring frequency": "Daily",
          "Last date": 43685,
          Age: "5 to 14",
          "Special notes": "Parents must stay",
          "Address 1": "Wexford",
          "Address 2": "Clonard Road",
          "Address 3": "Innovate Wexford Park",
          "Address 4": "",
          Postcode: "Y35 RT91",
          "Website/Facebook":
            "https://www.eventbrite.ie/e/cul-camp-for-kids-on-the-autism-spectrum-tickets-64062356232#",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Bounce-a-Lot",
          Category: "Activity",
          Organisation: "Bounce-a-Lot",
          "Member only?": "N",
          Banner: "Bouncy castle park",
          "Event details": "Closed session for special needs, siblings welcome",
          "": "",
          __1: "",
          "Cost €": 7,
          "When?":
            "11 to 12 on occasional Sundays, will be updated as new dates are announced",
          "First Date": "",
          Time: "11 to 12",
          "Recurs?": "Y",
          "Recurring frequency": "weekly",
          "Last date": "30/08/2019",
          Age: "4 to 12",
          "Special notes": "Parents must stay",
          "Address 1": "Kildare",
          "Address 2": "Celbridge",
          "Address 3": "Ballyoulster",
          "Address 4": "Dublin Road",
          Postcode: "",
          "Website/Facebook": "https://www.facebook.com/Celbridgefootball/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Bounce-a-Lot/KAN",
          Category: "Activity",
          Organisation: "Kildare Autism Network",
          "Member only?": "N",
          Banner: "Bouncy castle park",
          "Event details":
            "Closed session for special needs organised by Kildare Autism Network, siblings welcome",
          "": "",
          __1: "",
          "Cost €": "7 for non members, 5 for KAN members",
          "When?":
            "10 to 1130 on occassional Sundays, will be updated as new dates announced",
          "First Date": "",
          Time: "",
          "Recurs?": "Y",
          "Recurring frequency": "Dates tbc",
          "Last date": "n/a",
          Age: "4 to 12",
          "Special notes": "Parents must stay",
          "Address 1": "Kildare",
          "Address 2": "Celbridge",
          "Address 3": "Ballyoulster",
          "Address 4": "Dublin Road",
          Postcode: "",
          "Website/Facebook": "https://www.facebook.com/Celbridgefootball/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Liquid Therapy Summer",
          Category: "Activity",
          Organisation: "Liquid Therapy",
          "Member only?": "N",
          Banner: "Surf lessons for children with autism",
          "Event details":
            "Group surfing lessons, run over a week in Rossnowlagh or Bundoran. Spots are allocated on a first come first serve basis",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?": "2020 dates to be announced, usually over July/August",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "Every summer",
          "Last date": "",
          Age: "5 to 16",
          "Special notes":
            "Spots are allocated on a first come first serve basis",
          "Address 1": "Donegal",
          "Address 2": "Bundoran",
          "Address 3": "Strand",
          "Address 4": "",
          Postcode: "F94HK72",
          "Website/Facebook": "https://www.liquidtherapy.ie",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Jumpzone Liffey Valley",
          Category: "Activity",
          Organisation: "Jumpzone",
          "Member only?": "N",
          Banner: "Trampolining",
          "Event details":
            "Closed session for children with autism, parents must stay",
          "": "",
          __1: "",
          "Cost €": "?",
          "When?": "Thursdays 6.30pm to 7.30pm",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "KonfidentKidz",
          Category: "Activity",
          Organisation: "KonfidentKidz",
          "Member only?": "Y",
          Banner: "Confidence building",
          "Event details": "Drama and role play to build confidence",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "n/a",
          Time: "various",
          "Recurs?": "Y",
          "Recurring frequency": "",
          "Last date": "",
          Age: "4+",
          "Special notes": "",
          "Address 1": "Cork",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "https://konfidentkidz.ie/seo/asd-classes/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Autcraft",
          Category: "Activity",
          Organisation: "Autcraft",
          "Member only?": "N",
          Banner: "Minecraft",
          "Event details":
            "Minecraft environment of families with autism, Familes are assessed first, must own web version of Minecraft",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "https://www.autcraft.com/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Sensory Fun with Friends",
          Category: "Group",
          Organisation: "Sensory Fun with Friends",
          "Member only?": "Y",
          Banner: "Support group",
          "Event details":
            "Support group for parents of children with additional needs",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "MiContact",
          Category: "Other Resources",
          Organisation: "MiContact",
          "Member only?": "N",
          Banner: "App that helps people to learn to maintain eye contact",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "TippyTalk",
          Category: "Other Resources",
          Organisation: "TippyTalk",
          "Member only?": "N",
          Banner: "Communication app",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "99.99 a year",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "JumpBox",
          Category: "Activity",
          Organisation: "JumpBox",
          "Member only?": "N",
          Banner: "Trampolining",
          "Event details":
            "Inclusion jump sessions with low music and quieter environment. Parent/carer supervision required",
          "": "",
          __1: "",
          "Cost €": "",
          "When?":
            "6pm to 7pm on Thursdays and 12 pm to 1pm on Sundays, hours can change during school holidays",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "Twice a week",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "Down",
          "Address 2": "Banbridge",
          "Address 3": "4 Waringsford Road",
          "Address 4": "JumpBox",
          Postcode: "BY32 4EH",
          "Website/Facebook": "http://www.jumpboxxni.co.uk/InclusionJump",
          "Tel:": "",
          "Contact name": "Rec by Aisling Fitzmaurice, LinkedIn",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "w5",
          Category: "Autism Friendly",
          Organisation: "",
          "Member only?": "N",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "Belfast",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "Rec by Aisling Fitzmaurice, LinkedIn",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Sticky Fingers",
          Category: "",
          Organisation: "",
          "Member only?": "N",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "Monthly",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "Newry",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "Rec by Aisling Fitzmaurice, LinkedIn",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Newry swimming",
          Category: "Activity",
          Organisation: "Newry Leisure Centre",
          "Member only?": "N",
          Banner: "Swimming",
          "Event details":
            "Swimming sessions with reduced numbers in pool and fun floats",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": 43713,
          Time: "1800-1900 on Thursdays",
          "Recurs?": "Y",
          "Recurring frequency": "Weekly",
          "Last date": "n/a",
          Age:
            "All, but adults must accompany on a 1 to 1 basis for under fours and 1 to two basis if at least one child is over four",
          "Special notes": "",
          "Address 1": "Down",
          "Address 2": "Newry",
          "Address 3": "Cecil Street",
          "Address 4": "Newry Leisure Centre",
          Postcode: "BT35 6AU",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name":
            "https://www.newrymournedown.org/media/uploads/autisim_friendly_session_dlc_information_september_2019_(002).pdf",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Newry trampolining",
          Category: "Activity",
          Organisation: "Newry Leisure Centre",
          "Member only?": "N",
          Banner: "Trampolining",
          "Event details": "Trampoline",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "Mondays",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "Monthly",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "Down",
          "Address 2": "Newry",
          "Address 3": "Cecil Street",
          "Address 4": "Newry Leisure Centre",
          Postcode: "BT35 6AU",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "Rec by Aisling Fitzmaurice, LinkedIn",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Avail",
          Category: "Other Resources",
          Organisation: "Avail",
          "Member only?": "n",
          Banner: "App to support children in every day living",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "Via Ger Heffernan, LinkedIn",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Clonakilty",
          Category: "Autism Friendly town",
          Organisation: "",
          "Member only?": "n",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Clonmel Playground",
          Category: "Activity",
          Organisation: "",
          "Member only?": "N",
          Banner: "Sensory playground",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Best of Matz",
          Category: "Activity",
          Organisation: "Best of Matz",
          "Member only?": "N",
          Banner: "Play centre with sensory room",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "Meath",
          "Address 2": "Kells",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "http://www.bestomatz.ie/sensory-room.asp",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Radisson Sligo",
          Category: "Accomodation",
          Organisation: "Radisson",
          "Member only?": "n",
          Banner: "Bedroom with sensory area",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.radissonhotels.com/en-us/hotels/radisson-blu-sligo-spa?checkInDate=2019-11-01&checkOutDate=2019-11-02&adults%5B%5D=1&children%5B%5D=0&searchType=lowest&promotionCode=",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Clayton Sligo",
          Category: "Accomodation",
          Organisation: "Clayton Hotels",
          "Member only?": "n",
          Banner: "Sensory room",
          "Event details":
            "Sensory room in hotel with calming lights, fidget toys etc, accessible by code",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.claytonhotelsligo.com/leisure/sensory-room/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Clonakilty Park Hotel",
          Category: "Accomodation",
          Organisation: "Clonakility Park Hotel",
          "Member only?": "n",
          Banner: "Autism-friendly hotel",
          "Event details": "Sensory box, social stories, staff training",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.clonakiltyparkhotel.ie/autism-friendly.html",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Tayto Park",
          Category: "Autism Friendly",
          Organisation: "Tayto Park",
          "Member only?": "N",
          Banner: "Autism-friendly theme park",
          "Event details":
            "Fast-pass queuing system, discounted tickets for carers, occassional autism-friendly days with music turned down and sensory room available",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "Regular opening hours",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "http://www.taytopark.ie/visitor-information/disability-policy",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Dublin Zoo",
          Category: "Autism Friendly",
          Organisation: "Dublin Zoo",
          "Member only?": "N",
          Banner: "Autism-friendly zoo",
          "Event details": "Carers discount",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.abettertomorrow-lidl.ie/autism-aware-store/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Lidl",
          Category: "Autism Friendly",
          Organisation: "Lidl",
          "Member only?": "N",
          Banner: "Autism-friendly shopping",
          "Event details":
            "Reduced lighting, no music or announcements, priority queuing",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "6pm to 8pm Tuesdays",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "Lidl stores nationwide",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.abettertomorrow-lidl.ie/autism-aware-store/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Cork University Hospital",
          Category: "Healthcare",
          Organisation: "CUH",
          "Member only?": "N",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.echolive.ie/corknews/Autism-friendly-health-services-should-be-adopted-nationwide-8cee1b93-f565-45dc-ba04-00d63a514612-ds",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Ballynoe House",
          Category: "Accomodation",
          Organisation: "Ballynoe House",
          "Member only?": "N",
          Banner: "Sensory box, engagement on how to best accomodate families",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://ballynoehouse.ie/autism-friendly-accommodation-environment/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Mayo Autism Camp",
          Category: "Activity",
          Organisation: "",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "https://www.facebook.com/mayoautismcamp/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Friends of Autism/ADHD",
          Category: "Support",
          Organisation: "Friends of Autism/ADHD",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "reached out on facebook",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Sensational Kids",
          Category: "",
          Organisation: "",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "Paula Mac Aodghagain",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Watch House Cross Library",
          Category: "Activity",
          Organisation: "Watch House Cross Community Library",
          "Member only?": "N",
          Banner: "Sensory room",
          "Event details": "Sensory room in library",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?":
            "10.30am to 4.30pm Wed, Fri, Sat, 10.30 to 6pm Tues, Thurs, bookable for half hour slots",
          "First Date": "n/a",
          Time:
            "10.30 to 4.30pm Wed, Fri, Sat, 10.30 to 6pm Tues, Thurs, bookable for half hour slots",
          "Recurs?": "Yes",
          "Recurring frequency": "Daily",
          "Last date": "n/a",
          Age: "All, including adults",
          "Special notes":
            "Bookable for 30 min sessions by phonining 061 557726",
          "Address 1": "Limerick",
          "Address 2": "Kileely Road",
          "Address 3": "Watch House Cross Shopping Centre",
          "Address 4": "Watch House Cross Community Library",
          Postcode: "V94 NH51",
          "Website/Facebook":
            "http://www.limerickcity.ie/Library/WatchHouseCrossCommunityLibrary/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Titanic Belfast",
          Category: "",
          Organisation: "",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://titanicbelfast.com/Site/Accessibility.aspx",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "The Rainbow Club Cork",
          Category: "",
          Organisation: "",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Kerry Autism Action",
          Category: "",
          Organisation: "",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Surf2Heal Garretstown",
          Category: "Activity",
          Organisation: "Suft2Heal",
          "Member only?": "N",
          Banner: "Surfing camps and lessons on Garretstown beach, Kinsale",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.facebook.com/pg/Surf2Heal-Gtown-297334447472914/posts/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Open Spectrum Golf",
          Category: "Activity",
          Organisation: "Open Spectrum",
          "Member only?": "Y",
          Banner: "Golf",
          "Event details": "Golf lessons",
          "": "",
          __1: "",
          "Cost €": "?",
          "When?": "9am on Saturdays",
          "First Date": "Saturdays",
          Time: "9am",
          "Recurs?": "Yes",
          "Recurring frequency": "Weekly",
          "Last date": "",
          Age: "?",
          "Special notes": "",
          "Address 1": "Dublin",
          "Address 2": "Dublin 16",
          "Address 3": "Kellystown Road",
          "Address 4": "Stackstown Golf Club",
          Postcode: "D16 DP11",
          "Website/Facebook": "www.openspectrum.ie",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Open Spectrum Athletics",
          Category: "Activity",
          Organisation: "Open Spectrum",
          "Member only?": "Y",
          Banner: "Athletics",
          "Event details":
            "Athletics sessions with experienced instructor and volunteers",
          "": "",
          __1: "",
          "Cost €": 10,
          "When?": "Three 45 minute sessions on Saturday afternoons",
          "First Date": "TBC",
          Time: "Three 45 min sessions",
          "Recurs?": "Yes",
          "Recurring frequency": "weekly",
          "Last date": "n/a",
          Age: 43634,
          "Special notes": "",
          "Address 1": "Dublin",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "Irishtown Stadium",
          Postcode: "",
          "Website/Facebook": "www.openspectrum.ie",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Open Spectrum Surfing",
          Category: "Activity",
          Organisation: "Open Spectrum",
          "Member only?": "Y",
          Banner: "Surfing",
          "Event details":
            "Surfing lessons run in partnership with Brittas Bay Surf School",
          "": "",
          __1: "",
          "Cost €": "15 per sessions",
          "When?": "Two sessions in late summer. Dates vary.",
          "First Date": "Septembers",
          Time: "various",
          "Recurs?": "two sesssions in September",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "Wicklow",
          "Address 2": "Brittas Bay",
          "Address 3": "Brittas Bay Surf School",
          "Address 4": "",
          Postcode: "A67 WP96",
          "Website/Facebook": "www.openspectrum.ie",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Open Spectrum Wall Climbing",
          Category: "Activity",
          Organisation: "Open Spectrum",
          "Member only?": "Y",
          Banner: "Wall climbing",
          "Event details":
            "Wall climbing in small groups with ASD-experienced coach",
          "": "",
          __1: "",
          "Cost €": "?",
          "When?": "",
          "First Date": "n/a",
          Time:
            "45 minute sessions on Saturday afternoons, waiting list for new places",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "7 plus",
          "Special notes": "",
          "Address 1": "Dublin",
          "Address 2": "Dublin 4",
          "Address 3": "Stillorgan Road",
          "Address 4": "",
          Postcode: "D04 C7X2",
          "Website/Facebook": "www.openspectrum.ie",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Open Spectrium Jumpzone",
          Category: "Activity",
          Organisation: "Open Spectrum",
          "Member only?": "Y",
          Banner: "Jumpzone",
          "Event details": "Trampoline sessions with lights down low",
          "": "",
          __1: "",
          "Cost €": 10,
          "When?": "Nov 9 and Nov 23",
          "First Date": "Nov 9th, Nov 23rd",
          Time: "Saturdays during term time",
          "Recurs?": "during term time",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Inflatazone",
          Category: "Autism-friendly",
          Organisation: "Inflatazone",
          "Member only?": "Y",
          Banner: "Giant inflatable playzone",
          "Event details":
            "Autism-friendly venue for open bouncing, carers allowed on for free, helpful staff",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "4 to 12",
          "Special notes": "",
          "Address 1": "Dublin",
          "Address 2": "Dublin 12",
          "Address 3": "Nangor Road",
          "Address 4": "Nangor Road Business Park",
          Postcode: "D12 TNY6",
          "Website/Facebook": "https://inflatazone.ie/jump-zone-autism/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Inflatazone",
          Category: "Activity",
          Organisation: "Inflatazone",
          "Member only?": "Y",
          Banner: "Closed sensory sessions at giant inflatable playzone",
          "Event details": "Closed sessions for children with sensory needs",
          "": "",
          __1: "",
          "Cost €": "",
          "When?":
            "6.30pm to 7.30pm October 17, other dates to be added as announced",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "4 to 12",
          "Special notes": "",
          "Address 1": "Dublin",
          "Address 2": "Dublin 12",
          "Address 3": "Nangor Road",
          "Address 4": "Nangor Road Business Park",
          Postcode: "D12 TNY6",
          "Website/Facebook": "https://inflatazone.ie/jump-zone-autism/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Open Spectrum Teen group",
          Category: "Activity",
          Organisation: "Open Spectrum",
          "Member only?": "Y",
          Banner: "Teen Group",
          "Event details":
            "Teen group meeting monthly in the South County Dublin area, activities and venues vary by month",
          "": "",
          __1: "",
          "Cost €": "varies depending on activity",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "Monthly",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "varies",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "A Special Day Celbridge",
          Category: "Activity",
          Organisation: "A Special Day",
          "Member only?": "N",
          Banner: "Social group",
          "Event details":
            "Sensory play, art, baking, singing, stories and other activities",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?": "10am to 12pm on Saturdays",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "TBC",
          "Special notes": "",
          "Address 1": "Co Kildare",
          "Address 2": "Celbridge",
          "Address 3": "Celbridge Community Centre",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "A Special Day Dunboyne",
          Category: "Activity",
          Organisation: "A Special Day",
          "Member only?": "N",
          Banner: "Social group",
          "Event details":
            "Sensory play, art, baking, singing, stories and other activities",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?": "4.30pm to 5.30pm on Thursdays",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "TBC",
          "Special notes": "",
          "Address 1": "Co Meath",
          "Address 2": "Dunboyne",
          "Address 3": "",
          "Address 4": "St Peter's GAA Hall",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "A Special Day Kilcock",
          Category: "Activity",
          Organisation: "A Special Day",
          "Member only?": "N",
          Banner: "Social group",
          "Event details":
            "Sensory play, art, baking, singing, stories and other activities",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?": "7pm to 8pm on Thursdays",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "TBC",
          "Special notes": "",
          "Address 1": "Co Kildare",
          "Address 2": "Kilcock",
          "Address 3": "",
          "Address 4": "Kilocck GAA club",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "A Special Day Raheny",
          Category: "Activity",
          Organisation: "A Special Day",
          "Member only?": "N",
          Banner: "Social group",
          "Event details":
            "Sensory play, art, baking, singing, stories and other activities",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?": "10am to 11am on Saturdays",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "TBC",
          "Special notes": "",
          "Address 1": "Co Dublin",
          "Address 2": "Raheny",
          "Address 3": "",
          "Address 4": "The Grange Woodbine Club",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "A Special Day Dunboyne LifeSkills",
          Category: "Activity",
          Organisation: "A Special Day",
          "Member only?": "N",
          Banner: "Life skills",
          "Event details": "Road safety, personal care, shop skills and others",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?": "5.30pm to 6.30pm on Thursdays",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "TBC",
          "Special notes": "",
          "Address 1": "Co Meath",
          "Address 2": "Dunboyne",
          "Address 3": "",
          "Address 4": "St Peter's GAA Hall",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Kidzcraft",
          Category: "Activity",
          Organisation: "Kidzcraft",
          "Member only?": "N",
          Banner: "Social Group",
          "Event details": "Sensory play, art, social skills",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?": "Three sessions on Saturdays xx x",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "TBC",
          "Special notes": "",
          "Address 1": "Co Kildare",
          "Address 2": "Kill",
          "Address 3": "",
          "Address 4": "Saplings National School",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Helping Hands",
          Category: "Activity",
          Organisation: "Helping Hands",
          "Member only?": "N",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "Co Down",
          "Address 2": "Dundonald",
          "Address 3": "Millars Lane",
          "Address 4": "Autism Resource Centre",
          Postcode: "BT 16 2DA",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Tallaght Parents Autism Support Group",
          Category: "Support",
          Organisation: "Tallaght Parents Autism Support Group",
          "Member only?": "",
          Banner: "Support group",
          "Event details":
            "Monthly support meetings for parents and caregivers",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?": "7pm to 9pm on first Thursday of every month",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "Killinarden Community Centre",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Snowflakes Autism Support Horse-riding",
          Category: "Activity",
          Organisation: "Snowflakes Autism Support",
          "Member only?": "Y",
          Banner: "Horse-riding",
          "Event details":
            "Horse-riding lessons at theraputic riding centre for children autism, parents must stay",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?":
            "3.15pm to 4.15pm on Saturdays for five weeks in Oct/Nov, tuesdays 4.30pm to 5.30pm for five week term in October/November",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "4 plus",
          "Special notes": "",
          "Address 1": "Co Dublin",
          "Address 2": "Donabate",
          "Address 3": "Corballis Theraputic Riding Centre",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.facebook.com/pg/Snowflakesautismsupport/events/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Snowflakes Autism Support Swimming",
          Category: "Activity",
          Organisation: "Snowflakes Autism Support",
          "Member only?": "Y",
          Banner: "Swimming",
          "Event details": "Swimming lessons for children with autism",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?": "7pm to 8pm on Mondays from 9th September to 28th October",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "4 plus",
          "Special notes": "",
          "Address 1": "Dublin 17",
          "Address 2": "Belcamp",
          "Address 3": "Belcamp Lane",
          "Address 4": "St Michael's House Leisure Centre & Swimming Pool",
          Postcode: "",
          "Website/Facebook":
            "https://www.facebook.com/pg/Snowflakesautismsupport/events/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Snowflakes Autism Support wall-climbing",
          Category: "Activity",
          Organisation: "Snowflakes Autism Support",
          "Member only?": "Y",
          Banner: "Wall climbing",
          "Event details":
            "Wall climbing in small groups for children with autism",
          "": "",
          __1: "",
          "Cost €": "5 weeks for 70",
          "When?": "4pm to 5pm on Wednesdays for five weeks from October 16",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "6 plus",
          "Special notes": "",
          "Address 1": "Dublin 11",
          "Address 2": "Kildonan",
          "Address 3": "North Road",
          "Address 4": "North Park",
          Postcode: "Awesome Walls Dublin",
          "Website/Facebook":
            "https://www.facebook.com/pg/Snowflakesautismsupport/events/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Snowflakes Autism Support speech & drama",
          Category: "Activity",
          Organisation: "Snowflakes Autism Support",
          "Member only?": "Y",
          Banner: "Speech & Drama",
          "Event details": "Speech & drama lessons for children with autism",
          "": "",
          __1: "",
          "Cost €": "5 weeks for 50",
          "When?": "4.30pm to 5.30pm on Fridays from Nov 8th for five weeks",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "Holywell Community Centre",
          "Website/Facebook":
            "https://www.facebook.com/pg/Snowflakesautismsupport/events/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Snowflakes Autism Support sensory play",
          Category: "Activity",
          Organisation: "Snowflakes Autism Support",
          "Member only?": "Y",
          Banner: "Sensory play Saturdays",
          "Event details":
            "Whizzy dizzies, ball pit, balancing tools, sensory play mats, liquid tiles and more, siblings welcome",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?": "10am to 11.30am Saturdays",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "under 10s",
          "Special notes": "",
          "Address 1": "?",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Snowflakes Autism Support messy play",
          Category: "Activity",
          Organisation: "Snowflakes Autism Support",
          "Member only?": "Y",
          Banner: "Messy play",
          "Event details":
            "Finger painting, sand play, jelly bags, rainbow spaghetti and more",
          "": "",
          __1: "",
          "Cost €": "8 per child per session, or 21 for term of tree",
          "When?":
            "10.30am to 11.30am Saturday Sept 7, Oct 12, Nov 16, more dates to be added as announced",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "?",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Fettercairn Youth Horse Project",
          Category: "Autism-friendly",
          Organisation: "Fettercairn Youth Horse Riding",
          "Member only?": "N",
          Banner: "Horse-riding",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Sensory Fun with Friends Panto",
          Category: "Event",
          Organisation: "Sensory Fun with Friends",
          "Member only?": "Y",
          Banner: "Sensory-friendly Snow White",
          "Event details":
            "Quiet room for group plus sensory stories to prepare",
          "": "",
          __1: "",
          "Cost €": "TBC",
          "When?": "6.30pm Dec 17",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "Dublin 24",
          "Address 2": "Tallaght",
          "Address 3": "Belgard Square East",
          "Address 4": "The Civic",
          Postcode: "D24 NWN7",
          "Website/Facebook":
            "http://fyhp.ie/riding-lessons/equine-assisted-learning/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Sensory Fun with Friends Frozen II",
          Category: "Event",
          Organisation: "Sensory Fun with Friends",
          "Member only?": "Y",
          Banner: "Sensory-friendly showing of Frozen II",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "Nov 23",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "IMC Tallaght",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "County Library Tallaght",
          Category: "Event",
          Organisation: "County Library Tallaght",
          "Member only?": "N",
          Banner: "Sensory-friendly story time",
          "Event details":
            "Story telling incorporating assistive technology and toys",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "10.30am Nov 2",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "Dublin 24",
          "Address 2": "Tallaght",
          "Address 3": "Library Square",
          "Address 4": "County Library Tallaght",
          Postcode: "D24 A3EX",
          "Website/Facebook":
            "https://www.eventbrite.ie/o/county-library-tallaght-dublin-24-4238480119",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "County Library Tallaght",
          Category: "Activity",
          Organisation: "County Library Tallaght",
          "Member only?": "N",
          Banner: "ASD-friendly Lego workshop",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?": "3pm Sat Nov 2",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "Dublin 24",
          "Address 2": "Tallaght",
          "Address 3": "Library Square",
          "Address 4": "County Library Tallaght",
          Postcode: "D24 A3EX",
          "Website/Facebook":
            "https://www.eventbrite.ie/o/county-library-tallaght-dublin-24-4238480120",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "County Library Tallaght",
          Category: "Activity",
          Organisation: "County Library Tallaght",
          "Member only?": "N",
          Banner: "Yoga workshop",
          "Event details":
            "Yoga workshop for children with additional needs and their parents",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?": "2.30pm Nov 23",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "Dublin 24",
          "Address 2": "Tallaght",
          "Address 3": "Library Square",
          "Address 4": "County Library Tallaght",
          Postcode: "D24 A3EX",
          "Website/Facebook":
            "https://www.eventbrite.ie/o/county-library-tallaght-dublin-24-4238480121",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "County Library Tallaght",
          Category: "Event",
          Organisation: "County Library Tallaght",
          "Member only?": "N",
          Banner: "Self acceptance",
          "Event details":
            "Self acceptance for children and teenagers with hidden disabilities",
          "": "",
          __1: "",
          "Cost €": "Free",
          "When?": "7pm Nov 19",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "Children and teenagers",
          "Special notes": "",
          "Address 1": "Dublin 24",
          "Address 2": "Tallaght",
          "Address 3": "Library Square",
          "Address 4": "County Library Tallaght",
          Postcode: "D24 A3EX",
          "Website/Facebook":
            "https://www.eventbrite.ie/o/county-library-tallaght-dublin-24-4238480122",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Odeon Cinema Cavan",
          Category: "Activity",
          Organisation: "Odeon Cinema",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "11.30am one Sunday per month",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.odeoncinemas.ie/accessibility/autism-friendly-cinema-screenings/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Odeon Cinema Coolock",
          Category: "Activity",
          Organisation: "Odeon Cinema",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "11.30am one Sunday per month",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.odeoncinemas.ie/accessibility/autism-friendly-cinema-screenings/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Odeon Cinema Kilmarnock",
          Category: "Activity",
          Organisation: "Odeon Cinema",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "11.30am one Sunday per month",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.odeoncinemas.ie/accessibility/autism-friendly-cinema-screenings/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Odeon Cinema Limerick",
          Category: "Activity",
          Organisation: "Odeon Cinema",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "11.30am one Sunday per month",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.odeoncinemas.ie/accessibility/autism-friendly-cinema-screenings/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Odeon Cinema Naas",
          Category: "Activity",
          Organisation: "Odeon Cinema",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "11.30am one Sunday per month",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.odeoncinemas.ie/accessibility/autism-friendly-cinema-screenings/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Odeon Cinema Newark",
          Category: "Activity",
          Organisation: "Odeon Cinema",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "11.30am one Sunday per month",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.odeoncinemas.ie/accessibility/autism-friendly-cinema-screenings/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Odeon Cinema Stillorgan",
          Category: "Activity",
          Organisation: "Odeon Cinema",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "11.30am one Sunday per month",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.odeoncinemas.ie/accessibility/autism-friendly-cinema-screenings/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Odeon Cinema The Point",
          Category: "Activity",
          Organisation: "Odeon Cinema",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "11.30am one Sunday per month",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "All",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.odeoncinemas.ie/accessibility/autism-friendly-cinema-screenings/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Odeon Cinema Blanchardstown",
          Category: "Activity",
          Organisation: "Odeon Cinema",
          "Member only?": "",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "Monday evenings",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "More mature audience",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook":
            "https://www.odeoncinemas.ie/accessibility/autism-friendly-cinema-screenings/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "WASSA",
          Category: "Group",
          Organisation: "WASSA",
          "Member only?": "Y",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "10 to join",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "WASSA Swimming",
          Category: "Activity",
          Organisation: "WASSA",
          "Member only?": "Y",
          Banner: "Swimming",
          "Event details": "Swimming lessons for children with autism",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "Six or seven week blocks, with the school calendar",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "Splashworld",
          Postcode: "",
          "Website/Facebook": "http://www.wassa.ie/activities/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "WASSA Playcentre",
          Category: "Activity",
          Organisation: "WASSA",
          "Member only?": "Y",
          Banner: "Play centre sessions",
          "Event details":
            "Closed sessions at indoor play centre, siblings welcome",
          "": "",
          __1: "",
          "Cost €": "5 including food",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "Runamuck",
          Postcode: "",
          "Website/Facebook": "http://www.wassa.ie/activities/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "WASSA  bounce",
          Category: "Activity",
          Organisation: "WASSA",
          "Member only?": "Y",
          Banner: "Bouncy castle park",
          "Event details": "Closed sessions at bouncing session",
          "": "",
          __1: "",
          "Cost €": "5 including food",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "Megabounce",
          Postcode: "",
          "Website/Facebook": "http://www.wassa.ie/activities/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "WASSA Horse-riding",
          Category: "Activity",
          Organisation: "WASSA",
          "Member only?": "Y",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": 10,
          "When?": "Saturdays 4pm to 4.30pm and 4.30pm to 5pm",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "Kilotteran Equitation Centre",
          Postcode: "",
          "Website/Facebook": "http://www.wassa.ie/activities/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "WASSA Art classes",
          Category: "Activity",
          Organisation: "WASSA",
          "Member only?": "Y",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "http://www.wassa.ie/activities/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "WASSA Surfing",
          Category: "Activity",
          Organisation: "WASSA",
          "Member only?": "Y",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "http://www.wassa.ie/activities/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "WASSA Cookery",
          Category: "Activity",
          Organisation: "WASSA",
          "Member only?": "Y",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "http://www.wassa.ie/activities/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "WASSA Panto",
          Category: "Activity",
          Organisation: "WASSA",
          "Member only?": "Y",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "http://www.wassa.ie/activities/",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "WASSA Siblings club",
          Category: "Activity",
          Organisation: "WASSA",
          "Member only?": "Y",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        },
        {
          Name: "Omniplex Tralee",
          Category: "Activity",
          Organisation: "Omniplex",
          "Member only?": "N",
          Banner: "",
          "Event details": "",
          "": "",
          __1: "",
          "Cost €": "",
          "When?": "",
          "First Date": "",
          Time: "",
          "Recurs?": "",
          "Recurring frequency": "",
          "Last date": "",
          Age: "",
          "Special notes": "",
          "Address 1": "",
          "Address 2": "",
          "Address 3": "",
          "Address 4": "",
          Postcode: "",
          "Website/Facebook": "",
          "Tel:": "",
          "Contact name": "",
          "Contact details": "",
          "Follow up": ""
        }
      ]
    };
  },
  created() {
    let locations = this.items.map(item => [
      item["Address 1"],
      item["Address 2"],
      item["Address 3"]
    ]);
    if (locations.length) {
      // using concat() instead of flat() here to avoid some nuxt error
      this.locations = new Set([].concat(...locations).sort());
    }
    let ageRanges = this.items.map(item => [item["Age"]]);
    if (ageRanges.length) {
      this.ageRanges = new Set([].concat(...ageRanges).sort());
    }
  },

  methods: {
    search() {
      this.$search(this.searchTerm, this.items, this.searchOptions).then(
        results => {
          this.results = results;
        }
      );
    },
    searchFromClick(event) {
      this.searchTerm = event.target.textContent;
      scrollToElement("#search-top");
    },
    clear() {
      this.searchTerm = "";
      this.chosenLocation = "";
      this.chosenRange = "";
    }
  },
  watch: {
    searchTerm: function() {
      this.search();
    }
  },
  computed: {
    filteredResults: function() {
      let output;

      if (!this.searchTerm.length) {
        output = this.items;
      } else {
        output = this.results;
      }
      if (!this.chosenLocation.length && !this.chosenRange.length) {
        return output;
      }

      if (this.chosenLocation.length) {
        output = output.filter(result => {
          return (
            result["Address 1"] == this.chosenLocation ||
            result["Address 2"] == this.chosenLocation ||
            result["Address 3"] == this.chosenLocation
          );
        });
      }

      if (this.chosenRange.length) {
        if (this.chosenRange != "All") {
          output = output.filter(result => {
            return result["Age"] == this.chosenRange;
          });
        }
      }

      return output;
    }
  }
};
</script>

<style>
.search__wrap {
  width: 600px;
  max-width: 90vw;
  margin: 0 auto;
  margin-bottom: 600px;
}

.results-card {
  /* display: grid;
  grid-template-columns: repeat(auto-fit, minmax(166px, 1fr));
  grid-gap: 20px; */
  padding: 20px;
}

.results-card__wrap {
  box-shadow: 0px 0px 6px -3px rgba(0, 0, 0, 0.4);
}

.result-val {
  word-break: break-word;
}

.feature a.font-thin {
  font-weight: 200;
}

.clickable-val {
  cursor: pointer;
  color: green;
  text-align: left;
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.6s;
}
.fade-enter,
.fade-leave-active {
  opacity: 0;
}
</style>